version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "r4b2"
    groups:
      github-actions:
        patterns:
          - "*"
