name: Semver Tag

on:
  push:
    branches: ["main"]

jobs:
  semver-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"
      - name: Get the version
        id: vars
        run: echo ::set-output name=version::$(GitVersion /output json)
